package core

const (
	// LogRoll ...
	LogRoll = "API"
	// SessionName ...
	SessionName = "_sess"
	// SessionExpire ...
	SessionExpire = 60 * 60 * 24 * 3
	// SessionKeyUserID ...
	SessionKeyUserID = "id"
)
